CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Ibbis" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "Description" text NOT NULL,
    "DOB" text NOT NULL,
    "Img" text NOT NULL,
    CONSTRAINT "PK_Ibbis" PRIMARY KEY ("Id")
);

CREATE TABLE "Educations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EducationName" text NOT NULL,
    "Description" text NOT NULL,
    "EducationSite" text NOT NULL,
    "Degree" text NOT NULL,
    "Duration" text NOT NULL,
    "IbbiId" integer NOT NULL,
    CONSTRAINT "PK_Educations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Educations_Ibbis_IbbiId" FOREIGN KEY ("IbbiId") REFERENCES "Ibbis" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Languages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "IbbiId" integer NOT NULL,
    CONSTRAINT "PK_Languages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Languages_Ibbis_IbbiId" FOREIGN KEY ("IbbiId") REFERENCES "Ibbis" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "PriorityView" integer NOT NULL,
    "Img" text NOT NULL,
    "Description" text NOT NULL,
    "Date" text NOT NULL,
    "Role" text NOT NULL,
    "IbbiId" integer NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Projects_Ibbis_IbbiId" FOREIGN KEY ("IbbiId") REFERENCES "Ibbis" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ResumeExperiences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyName" text NOT NULL,
    "CompanyLocation" text NOT NULL,
    "Position" text NOT NULL,
    "Duration" text NOT NULL,
    "Description" text NOT NULL,
    "IbbiId" integer NOT NULL,
    CONSTRAINT "PK_ResumeExperiences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ResumeExperiences_Ibbis_IbbiId" FOREIGN KEY ("IbbiId") REFERENCES "Ibbis" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Socials" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Img" text NOT NULL,
    "IbbiId" integer NOT NULL,
    CONSTRAINT "PK_Socials" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Socials_Ibbis_IbbiId" FOREIGN KEY ("IbbiId") REFERENCES "Ibbis" ("Id") ON DELETE CASCADE
);

INSERT INTO "Ibbis" ("Id", "DOB", "Description", "FirstName", "Img")
VALUES (1, '18.04.2001', 'This is me', 'Ibrahima Secka', '');

CREATE INDEX "IX_Educations_IbbiId" ON "Educations" ("IbbiId");

CREATE INDEX "IX_Languages_IbbiId" ON "Languages" ("IbbiId");

CREATE INDEX "IX_Projects_IbbiId" ON "Projects" ("IbbiId");

CREATE INDEX "IX_ResumeExperiences_IbbiId" ON "ResumeExperiences" ("IbbiId");

CREATE INDEX "IX_Socials_IbbiId" ON "Socials" ("IbbiId");

SELECT setval(
    pg_get_serial_sequence('"Ibbis"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Ibbis") + 1,
        nextval(pg_get_serial_sequence('"Ibbis"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251006091015_PriorityViewInProject2', '9.0.2');

COMMIT;

