// <auto-generated />
using CV.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CV.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250217093402_DevAndProd")]
    partial class DevAndProd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CV.Models.Education", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EducationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EducationSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IbbiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IbbiId");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("CV.Models.Ibbi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ibbis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DOB = "18.04.2001",
                            Description = "This is me",
                            FirstName = "Ibrahima Secka",
                            Img = ""
                        });
                });

            modelBuilder.Entity("CV.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IbbiId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IbbiId");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("CV.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IbbiId")
                        .HasColumnType("integer");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IbbiId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("CV.Models.ResumeExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IbbiId")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IbbiId");

                    b.ToTable("ResumeExperience");
                });

            modelBuilder.Entity("CV.Models.Social", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IbbiId")
                        .HasColumnType("integer");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IbbiId");

                    b.ToTable("Social");
                });

            modelBuilder.Entity("CV.Models.Education", b =>
                {
                    b.HasOne("CV.Models.Ibbi", "Ibbi")
                        .WithMany("Educations")
                        .HasForeignKey("IbbiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ibbi");
                });

            modelBuilder.Entity("CV.Models.Language", b =>
                {
                    b.HasOne("CV.Models.Ibbi", "Ibbi")
                        .WithMany("Languages")
                        .HasForeignKey("IbbiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ibbi");
                });

            modelBuilder.Entity("CV.Models.Project", b =>
                {
                    b.HasOne("CV.Models.Ibbi", "Ibbi")
                        .WithMany("Projects")
                        .HasForeignKey("IbbiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ibbi");
                });

            modelBuilder.Entity("CV.Models.ResumeExperience", b =>
                {
                    b.HasOne("CV.Models.Ibbi", "Ibbi")
                        .WithMany("resumeExperiences")
                        .HasForeignKey("IbbiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ibbi");
                });

            modelBuilder.Entity("CV.Models.Social", b =>
                {
                    b.HasOne("CV.Models.Ibbi", "Ibbi")
                        .WithMany("Socials")
                        .HasForeignKey("IbbiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ibbi");
                });

            modelBuilder.Entity("CV.Models.Ibbi", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Languages");

                    b.Navigation("Projects");

                    b.Navigation("Socials");

                    b.Navigation("resumeExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
